# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

# on:
#   - push

jobs:
  test:
    environment: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r dev-requirements.txt
        pip install -U py-cord==2.3.0
    - name: Test with pytest
      working-directory: ./tests
      env:
        SLOTH_DB_HOST: ${{ secrets.SLOTH_DB_HOST }}
        SLOTH_DB_USER: ${{ secrets.SLOTH_DB_USER }}
        SLOTH_DB_PASSWORD: ${{ secrets.SLOTH_DB_PASSWORD }}
        SLOTH_DB_NAME: ${{ secrets.SLOTH_DB_NAME }}
        TEACHER_ROLE_ID: ${{ secrets.TEACHER_ROLE_ID }}
        BOTS_AND_COMMANDS_CHANNEL_ID: ${{ secrets.BOTS_AND_COMMANDS_CHANNEL_ID }}
        TEACHER_FEEDBACK_THREAD_ID: ${{ secrets.TEACHER_FEEDBACK_THREAD_ID }}
      run: |
        pytest